---
# jenkins
#
# Provision a Jenkins worker instance.
# - When sitespeed_worker is set, only apply the configuraiton necessary for running sitespeed.io
# - When platform_worker is set, the resulting instance can run edx-platform tests

# All jenkins workers
- include: packer.yml
- include: system.yml
- include: python.yml

# only platform workers
- include: python_platform_worker.yml
  when: platform_worker is defined

# only loadtest driver workers
- include: loadtest_driver_worker.yml
  when: loadtest_driver_worker is defined
